import json

notebook_path = "main_multi_attention.ipynb"

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find where the deep learning pipeline starts
# Cell 12 in the user's list was "SUPER-FAST NUMPY PIPELINE"
# We will truncate the notebook before cell 12, and append our PyTorch cells.

# Let's search for the cell that contains "SUPER-FAST NUMPY PIPELINE"
target_idx = -1
for i, cell in enumerate(nb['cells']):
    source = "".join(cell.get('source', []))
    if "SUPER-FAST NUMPY PIPELINE" in source:
        target_idx = i
        break

if target_idx != -1:
    # Keep everything up to the Numpy Pipeline cell (exclusive)
    nb['cells'] = nb['cells'][:target_idx]
    
    # Add PyTorch Imports cell (if not present)
    torch_import = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =====================================================================\n",
            "# PYTORCH SETUP & ZERO-RAM DATASET (Memory Mapped)\n",
            "# =====================================================================\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.optim as optim\n",
            "from torch.utils.data import Dataset, DataLoader, ConcatDataset\n",
            "\n",
            "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "print(f\"Using device: {DEVICE}\")\n",
            "\n",
            "class MMAPDataset(Dataset):\n",
            "    def __init__(self, aud_path, vid_path, y_path, is_samm=False):\n",
            "        self.is_samm = is_samm\n",
            "        self.vid = np.load(vid_path, mmap_mode='r')\n",
            "        self.y = np.load(y_path, mmap_mode='r')\n",
            "        \n",
            "        if not is_samm:\n",
            "            self.aud = np.load(aud_path, mmap_mode='r')\n",
            "        else:\n",
            "            self.aud = None\n",
            "            \n",
            "        self.length = len(self.y)\n",
            "        \n",
            "    def __len__(self):\n",
            "        return self.length\n",
            "        \n",
            "    def __getitem__(self, idx):\n",
            "        if self.is_samm:\n",
            "            a = torch.zeros((150, 136, 1), dtype=torch.float32)\n",
            "        else:\n",
            "            a = torch.from_numpy(np.array(self.aud[idx])).float()\n",
            "            \n",
            "        v = torch.from_numpy(np.array(self.vid[idx])).float()\n",
            "        \n",
            "        y_vec = self.y[idx]\n",
            "        y_class = np.argmax(y_vec)\n",
            "        return a, v, torch.tensor(y_class, dtype=torch.long)\n",
            "\n",
            "# NOTE: Make sure you ran unpack_datasets.py to extract the NPZ files to NPY first!\n",
            "print(\"Loading datasets using Memory Mapping...\")\n",
            "d1 = MMAPDataset('unpacked_ravdess/aud.npy', 'unpacked_ravdess/vid.npy', 'unpacked_ravdess/y.npy')\n",
            "d2 = MMAPDataset('unpacked_samm/vid.npy', 'unpacked_samm/vid.npy', 'unpacked_samm/y.npy', is_samm=True)\n",
            "d3 = MMAPDataset('unpacked_cremad/aud.npy', 'unpacked_cremad/vid.npy', 'unpacked_cremad/y.npy')\n",
            "\n",
            "full_dataset = ConcatDataset([d1, d2, d3])\n",
            "train_size = int(0.8 * len(full_dataset))\n",
            "val_size = len(full_dataset) - train_size\n",
            "train_dataset, val_dataset = torch.utils.data.random_split(full_dataset, [train_size, val_size])\n",
            "\n",
            "BATCH_SIZE = 32\n",
            "train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)\n",
            "val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)\n",
            "print(f\"DataLoaders ready! Total samples: {len(full_dataset)}\")\n"
        ]
    }
    
    torch_model = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =====================================================================\n",
            "# PYTORCH QUAD-MODAL ARCHITECTURE\n",
            "# =====================================================================\n",
            "class AudioBranch(nn.Module):\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        self.conv1 = nn.Conv2d(1, 32, 3, padding=1)\n",
            "        self.bn1 = nn.BatchNorm2d(32)\n",
            "        self.pool1 = nn.MaxPool2d(2)\n",
            "        self.drop1 = nn.Dropout(0.2)\n",
            "\n",
            "        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)\n",
            "        self.bn2 = nn.BatchNorm2d(64)\n",
            "        self.pool2 = nn.MaxPool2d(2)\n",
            "        self.drop2 = nn.Dropout(0.25)\n",
            "\n",
            "        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)\n",
            "        self.bn3 = nn.BatchNorm2d(128)\n",
            "        self.pool3 = nn.MaxPool2d(2)\n",
            "        self.drop3 = nn.Dropout(0.3)\n",
            "\n",
            "        self.conv4 = nn.Conv2d(128, 128, 3, padding=1)\n",
            "        self.bn4 = nn.BatchNorm2d(128)\n",
            "\n",
            "        self.conv1d_1 = nn.Conv1d(2176, 64, 1, padding=0)\n",
            "        self.bn5 = nn.BatchNorm1d(64)\n",
            "        self.drop4 = nn.Dropout(0.3)\n",
            "        self.conv1d_2 = nn.Conv1d(64, 32, 3, padding=1)\n",
            "        self.bn6 = nn.BatchNorm1d(32)\n",
            "        \n",
            "        self.dense = nn.Linear(32, 128)\n",
            "        self.relu = nn.ReLU()\n",
            "\n",
            "    def forward(self, x):\n",
            "        x = x.permute(0, 3, 1, 2)\n",
            "        x = self.drop1(self.pool1(self.relu(self.bn1(self.conv1(x)))))\n",
            "        x = self.drop2(self.pool2(self.relu(self.bn2(self.conv2(x)))))\n",
            "        x = self.drop3(self.pool3(self.relu(self.bn3(self.conv3(x)))))\n",
            "        x = self.relu(self.bn4(self.conv4(x)))\n",
            "        \n",
            "        B, C, H, W = x.size()\n",
            "        x = x.permute(0, 2, 3, 1).contiguous()\n",
            "        x = x.view(B, H, W * C)\n",
            "        \n",
            "        x = x.permute(0, 2, 1)\n",
            "        x = self.drop4(self.relu(self.bn5(self.conv1d_1(x))))\n",
            "        x = self.relu(self.bn6(self.conv1d_2(x)))\n",
            "        \n",
            "        x = x.mean(dim=2)\n",
            "        x = self.relu(self.dense(x))\n",
            "        return x\n",
            "\n",
            "class SeparableConv2d(nn.Module):\n",
            "    def __init__(self, in_channels, out_channels):\n",
            "        super().__init__()\n",
            "        self.depthwise = nn.Conv2d(in_channels, in_channels, 3, padding=1, groups=in_channels)\n",
            "        self.pointwise = nn.Conv2d(in_channels, out_channels, 1)\n",
            "    def forward(self, x):\n",
            "        return self.pointwise(self.depthwise(x))\n",
            "\n",
            "class VideoBranch(nn.Module):\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        self.conv1 = SeparableConv2d(30, 32)\n",
            "        self.bn1 = nn.BatchNorm2d(32)\n",
            "        self.pool1 = nn.MaxPool2d(2)\n",
            "        self.drop1 = nn.Dropout(0.25)\n",
            "        \n",
            "        self.conv2 = SeparableConv2d(32, 64)\n",
            "        self.bn2 = nn.BatchNorm2d(64)\n",
            "        self.pool2 = nn.MaxPool2d(2)\n",
            "        self.drop2 = nn.Dropout(0.35)\n",
            "        \n",
            "        self.conv3 = SeparableConv2d(64, 128)\n",
            "        self.bn3 = nn.BatchNorm2d(128)\n",
            "        self.drop3 = nn.Dropout(0.4)\n",
            "        \n",
            "        self.dense = nn.Linear(128, 128)\n",
            "        self.relu = nn.ReLU()\n",
            "\n",
            "    def forward(self, x):\n",
            "        x = x.permute(0, 3, 1, 2)\n",
            "        x = self.drop1(self.pool1(self.relu(self.bn1(self.conv1(x)))))\n",
            "        x = self.drop2(self.pool2(self.relu(self.bn2(self.conv2(x)))))\n",
            "        x = self.drop3(self.relu(self.bn3(self.conv3(x))))\n",
            "        \n",
            "        x = x.mean(dim=[2, 3])\n",
            "        x = self.relu(self.dense(x))\n",
            "        return x\n",
            "\n",
            "class SEBlock(nn.Module):\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        self.fc1 = nn.Linear(128, 32)\n",
            "        self.fc2 = nn.Linear(32, 128)\n",
            "        self.relu = nn.ReLU()\n",
            "        self.sigmoid = nn.Sigmoid()\n",
            "    def forward(self, x):\n",
            "        sq = x.mean(dim=1)\n",
            "        ex = self.relu(self.fc1(sq))\n",
            "        ex = self.sigmoid(self.fc2(ex)).unsqueeze(1)\n",
            "        return x * ex\n",
            "\n",
            "class QuadModalModel(nn.Module):\n",
            "    def __init__(self, num_classes=6):\n",
            "        super().__init__()\n",
            "        self.audio = AudioBranch()\n",
            "        self.video = VideoBranch()\n",
            "        self.se = SEBlock()\n",
            "        \n",
            "        self.attn = nn.MultiheadAttention(embed_dim=128, num_heads=4, batch_first=True)\n",
            "        \n",
            "        self.fc1 = nn.Linear(128 * 2, 128)\n",
            "        self.drop1 = nn.Dropout(0.4)\n",
            "        self.fc2 = nn.Linear(128, 64)\n",
            "        self.drop2 = nn.Dropout(0.2)\n",
            "        self.out = nn.Linear(64, num_classes)\n",
            "        self.relu = nn.ReLU()\n",
            "\n",
            "    def forward(self, aud, vid):\n",
            "        a = self.audio(aud).unsqueeze(1)\n",
            "        v = self.video(vid).unsqueeze(1)\n",
            "        \n",
            "        x = torch.cat([a, v], dim=1)\n",
            "        x = self.se(x)\n",
            "        \n",
            "        attn_out, _ = self.attn(x, x, x)\n",
            "        x = x + attn_out\n",
            "        \n",
            "        x = x.view(x.size(0), -1)\n",
            "        x = self.drop1(self.relu(self.fc1(x)))\n",
            "        x = self.drop2(self.relu(self.fc2(x)))\n",
            "        return self.out(x)\n",
            "\n",
            "model = QuadModalModel(num_classes=6).to(DEVICE)\n",
            "print(\"PyTorch Model Architecture Ready!\")\n"
        ]
    }
    
    torch_train = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =====================================================================\n",
            "# PYTORCH TRAINING LOOP & FOCAL LOSS\n",
            "# =====================================================================\n",
            "import time\n",
            "\n",
            "class FocalLoss(nn.Module):\n",
            "    def __init__(self, gamma=2.0, label_smoothing=0.08):\n",
            "        super().__init__()\n",
            "        self.gamma = gamma\n",
            "        self.ce = nn.CrossEntropyLoss(label_smoothing=label_smoothing, reduction='none')\n",
            "        \n",
            "    def forward(self, inputs, targets):\n",
            "        ce_loss = self.ce(inputs, targets)\n",
            "        pt = torch.exp(-ce_loss)\n",
            "        return (((1 - pt) ** self.gamma) * ce_loss).mean()\n",
            "\n",
            "criterion = FocalLoss(gamma=2.0, label_smoothing=0.08)\n",
            "optimizer = optim.Adam(model.parameters(), lr=3e-4)\n",
            "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.3, patience=3, min_lr=1e-6)\n",
            "\n",
            "EPOCHS = 40\n",
            "PATIENCE = 10\n",
            "best_val_acc = 0.0\n",
            "patience_counter = 0\n",
            "\n",
            "print(\"Starting PyTorch Memory-Safe Training...\")\n",
            "for epoch in range(EPOCHS):\n",
            "    model.train()\n",
            "    train_loss, train_correct, train_total = 0, 0, 0\n",
            "    start_time = time.time()\n",
            "    \n",
            "    for batch_idx, (a, v, y) in enumerate(train_loader):\n",
            "        a, v, y = a.to(DEVICE), v.to(DEVICE), y.to(DEVICE)\n",
            "        \n",
            "        optimizer.zero_grad()\n",
            "        outputs = model(a, v)\n",
            "        loss = criterion(outputs, y)\n",
            "        loss.backward()\n",
            "        optimizer.step()\n",
            "        \n",
            "        train_loss += loss.item()\n",
            "        _, predicted = outputs.max(1)\n",
            "        train_total += y.size(0)\n",
            "        train_correct += predicted.eq(y).sum().item()\n",
            "        \n",
            "        if batch_idx % 20 == 0:\n",
            "            print(f\"Epoch [{epoch+1}/{EPOCHS}] Batch {batch_idx}/{len(train_loader)} Loss: {loss.item():.4f}\")\n",
            "            \n",
            "    model.eval()\n",
            "    val_loss, val_correct, val_total = 0, 0, 0\n",
            "    with torch.no_grad():\n",
            "        for a, v, y in val_loader:\n",
            "            a, v, y = a.to(DEVICE), v.to(DEVICE), y.to(DEVICE)\n",
            "            outputs = model(a, v)\n",
            "            loss = criterion(outputs, y)\n",
            "            val_loss += loss.item()\n",
            "            _, predicted = outputs.max(1)\n",
            "            val_total += y.size(0)\n",
            "            val_correct += predicted.eq(y).sum().item()\n",
            "            \n",
            "    train_acc = 100. * train_correct / train_total\n",
            "    val_acc = 100. * val_correct / val_total\n",
            "    avg_val_loss = val_loss / len(val_loader)\n",
            "    \n",
            "    scheduler.step(avg_val_loss)\n",
            "    epoch_time = time.time() - start_time\n",
            "    print(f\"\\nEpoch {epoch+1} Summary ({epoch_time:.1f}s):\")\n",
            "    print(f\"Train Acc: {train_acc:.2f}% | Train Loss: {train_loss/len(train_loader):.4f}\")\n",
            "    print(f\"Val Acc:   {val_acc:.2f}% | Val Loss:   {avg_val_loss:.4f}\\n\")\n",
            "    \n",
            "    if val_acc > best_val_acc:\n",
            "        print(f\"⭐ Validation Accuracy improved to {val_acc:.2f}%. Saving model!\")\n",
            "        best_val_acc = val_acc\n",
            "        torch.save(model.state_dict(), 'best_pytorch_model.pt')\n",
            "        patience_counter = 0\n",
            "    else:\n",
            "        patience_counter += 1\n",
            "        if patience_counter >= PATIENCE:\n",
            "            print(f\"Early stopping triggered at epoch {epoch+1}\")\n",
            "            break\n"
        ]
    }
    
    nb['cells'].extend([torch_import, torch_model, torch_train])
    
    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
        
    print(f"Successfully updated {notebook_path} with PyTorch architecture!")
else:
    print("Could not find the target cell to replace.")
